const personalities: Record<string, string[]> = {
  'berry-sky': [
    'Dreamy energy. Big playlist opinions.',
    'Brunch loyalist. Vision board pro.',
    'Pastel-coded. Chaos-controlled.',
    'Soft on the outside. Main character inside.',
    'Horoscope curious. Main feed aesthetic.',
    'Colorful thoughts. Zero chill (in a good way).',
  ],
  'cotton-check': [
    'Cozy structure. Planner filled to the edge.',
    'Calm face. Spreadsheet brain.',
    'Color tabs. High standards.',
    'Warm beverage. Cold logic.',
    'Organized chaos. Checkmark serotonin.',
    'Quiet power. Fully indexed.',
  ],
  'rosy-haze': [
    'Tender thoughts. Bold highlights.',
    'Soft heart. Sharp timing.',
    'Sentimental, but strategic.',
    'Feels everything. Plans anyway.',
    'Pastel brain. Playlist soul.',
    'Gentle energy. Efficient chaos.',
  ],
  'blue-dream': [
    'Cool calm. Silent authority.',
    'Aesthetic discipline. Crisp spacing.',
    'Fountain pen energy. Emotional stability.',
    'Quiet excellence. Perfect margins.',
    'Deep breath. Deeper thoughts.',
    'Understated. Unshakable.',
  ],
  'aloe-dew': [
    'Chill mode. Strong core.',
    'Soft glow. Deep roots.',
    'Hydrated. Grounded. Healing.',
    'Slow morning. Sharp instincts.',
    'Plant parent. People pro.',
    'Calm exterior. Wild ideas.',
  ],
  'grape-juice': [
    'Mystery. Sparkle. Sass.',
    'Quiet storm. Strong opinions.',
    'Aesthetic authority. Chaos optional.',
    'Plot twist energy.',
    'Sharp wit. Soft edges.',
    'Dramatic… but tasteful.',
  ],
  'peach-cream': [
    'Polite chaos. Glittering focus.',
    'Soft voice. Sharp planner.',
    'Pastel drive. Full-schedule heart.',
    'Encouraging, but spreadsheeted.',
    'Warm tones. Cold precision.',
    'Stickers ready. Goals locked.',
  ],
  'cloud-puff': [
    'Whimsical workflow. Intentional softness.',
    'Fluffy thoughts. Clear plans.',
    'Daydreamer with deadlines.',
    'Tender checklist energy.',
    'Soft chaos. Big plans.',
    'Cloud core. Clarity mode.',
  ],
};

export default personalities;
